BF: announce two tests xfail on windows python 3.13
See e.g.

https://github.com/dandi/dandi-cli/actions/runs/17147460699/job/48646355661

    ERROR dandi/cli/tests/test_cmd_validate.py::test_validate_nwb_path_grouping - AssertionError: Error: No module named '_posixsubprocess'
    ERROR dandi/tests/test_fixtures.py::test_organized_nwb_dir2 - AssertionError: Error: No module named '_posixsubprocess'

where it is due to not us but 'multiprocessing'

      File "C:\hostedtoolcache\windows\Python\3.13.7\x64\Lib\multiprocessing\resource_tracker.py", line 261, in _send
        self._ensure_running_and_write(msg)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
      File "C:\hostedtoolcache\windows\Python\3.13.7\x64\Lib\multiprocessing\resource_tracker.py", line 220, in _ensure_running_and_write
        self._launch()
        ~~~~~~~~~~~~^^
      File "C:\hostedtoolcache\windows\Python\3.13.7\x64\Lib\multiprocessing\resource_tracker.py", line 185, in _launch
        pid = util.spawnv_passfds(exe, args, fds_to_pass)
      File "C:\hostedtoolcache\windows\Python\3.13.7\x64\Lib\multiprocessing\util.py", line 515, in spawnv_passfds
        import _posixsubprocess
    ModuleNotFoundError: No module named '_posixsubprocess'

I think it is this upstream

https://github.com/python/cpython/issues/138031