BF: remove --doctest-modules
causes pytest to forbid running tests in submodules... we would need some RF to
happen first for that to be used:

$> python -m pytest -v dandi/cli
======================================================================================================= test session starts =======================================================================================================
platform linux -- Python 3.8.5, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/yoh/proj/dandi/dandi-cli/.hypothesis/examples')
rootdir: /home/yoh/proj/dandi/dandi-cli, inifile: pytest.ini
plugins: mock-3.2.0, cov-2.10.0, xdist-1.32.0, timeout-1.3.3, forked-1.1.3, hypothesis-4.36.2
collected 8 items / 2 errors / 6 selected

============================================================================================================= ERRORS ==============================================================================================================
___________________________________________________________________________________________ ERROR collecting dandi/cli/cmd_download.py ____________________________________________________________________________________________
dandi/cli/cmd_download.py:4: in <module>
    from .command import devel_option, main, map_to_click_exceptions
dandi/cli/command.py:222: in <module>
    from .cmd_download import download  # noqa: E402, F401
E   ImportError: cannot import name 'download' from partially initialized module 'dandi.cli.cmd_download' (most likely due to a circular import) (/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_download.py)
___________________________________________________________________________________________ ERROR collecting dandi/cli/cmd_register.py ____________________________________________________________________________________________
dandi/cli/cmd_register.py:3: in <module>
    from .command import (
dandi/cli/command.py:224: in <module>
    from .cmd_register import register  # noqa: E402, F401
E   ImportError: cannot import name 'register' from partially initialized module 'dandi.cli.cmd_register' (most likely due to a circular import) (/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_register.py)